language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services: mongodb

before_script:
  - pecl install gearman
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload -o
  - php artisan dump-autoload
  - php artisan cache:clear

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
